### PR TITLE
Change organization name to Ray Wenderlich

### PR DESCRIPTION
**Pull request by freak4pc**
Seems like the starter project still uses Razeware for the project name

### CODE REVIEW

**Comment by freak4pc** [comment]
cc/ @obuseme if you'll have the time. Thanks :)

**Comment by sberrevoets** [comment]
@rwenderlich can you confirm "Ray Wenderlich" should be the organization and not Razeware?

**Comment by freak4pc** [comment]
@sberrevoets See here: 
https://github.com/raywenderlich/swift-style-guide#organization-and-bundle-identifier

**Comment by sberrevoets** [comment]
Ah great call, thanks for submitting!

**Pull request merged**
